version: '3.9'

services:
  server:
    build:
      context: .
      dockerfile: cmd/server/Dockerfile
    ports:
      - "8080:8080"

  client:
    build:
      context: .
      dockerfile: cmd/client/Dockerfile
    depends_on:
      - server
    environment:
      - SERVER_URL=server:8080
